spring:
  application:
    name: api-simulator
  profiles:
    active: dev
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: false
    show-sql: true
